### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by pyama2000** [pyama2000/dotfiles#1]
- [x] Add keymapings
    - [x] Split Window 
    - [x] Create tab and move tab
- [ ] Make documents how to install and use these tools
- [x] (.config/coc/) Link only necessary files
